name: Packer Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get remove containerd
        sudo apt-get remove containerd.io
        sudo apt-get install docker.io
        sudo systemctl restart docker
        sudo systemctl status docker

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        packer init docker-image.pkr.hcl
        packer fmt docker-image.pkr.hcl
        packer validate docker-image.pkr.hcl
        packer build docker-image.pkr.hcl
        docker push shanumbra/dev:latest

    - name: Delete Dangling Images
      run: docker image prune -f --filter "dangling=true"
