name: Packer Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    if: false # Change to true to enable the workflow - temporarily disabled to avoid unnecessary builds
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get remove containerd
        sudo apt-get remove containerd.io
        sudo apt-get install docker.io
        sudo systemctl restart docker
        sudo systemctl status docker

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        packer init docker-image.pkr.hcl
        packer fmt docker-image.pkr.hcl
        packer validate docker-image.pkr.hcl
        packer build docker-image.pkr.hcl
        docker push shanumbra/dev:latest
