name: Packer Build and Push

on:
  push:
    branches:
      - main

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get remove containerd
        sudo apt-get remove containerd.io
        sudo apt-get instal docker.io
        sudo systemctl restart docker
        sudo systemctl status docker

    - name: Packer Initialize
      run: packer init docker-image.pkr.hcl

  format:
    runs-on: ubuntu-latest
    needs: initialize
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Packer Format
      run: packer fmt docker-image.pkr.hcl

  validate:
    runs-on: ubuntu-latest
    needs: format
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Packer Validate
      run: packer validate docker-image.pkr.hcl

  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Packer Build
      run: packer build docker-image.pkr.hcl

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
      run: docker push shanumbra/dev:latest

  delete:
    runs-on: ubuntu-latest
    needs: push
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delete Dangling Images
      run: docker image prune -f --filter "dangling=true"
